### ISSUE TITLE
provider panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mpalu** [exoscale/terraform-provider-exoscale#151]
Hello guys, 

We are receiving the following error using the latest version of the provider, while creating some amount of sks_nodepools resources (12 nodepools). Tested on macOS and Linux with the same result.

```
Stack trace from the terraform-provider-exoscale_v0.31.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x13cf625]

goroutine 330 [running]:
github.com/exoscale/egoscale/v2.sksNodepoolFromAPI(0xc0008d8f28)
        github.com/exoscale/egoscale@v0.84.3/v2/sks_nodepool.go:125 +0x2a5
github.com/exoscale/egoscale/v2.sksClusterFromAPI.func3(0xc0001a0cb0)
        github.com/exoscale/egoscale@v0.84.3/v2/sks_cluster.go:116 +0x145
github.com/exoscale/egoscale/v2.sksClusterFromAPI(0xc0001a0cb0, {0xc000458cb0, 0x8})
        github.com/exoscale/egoscale@v0.84.3/v2/sks_cluster.go:120 +0xa8
github.com/exoscale/egoscale/v2.(*Client).GetSKSCluster(0xc0003edda0, {0x1b42d20, 0xc0003b40c0}, {0xc000458cb0, 0x8}, {0xc00052c8a0, 0x24})
        github.com/exoscale/egoscale@v0.84.3/v2/sks_cluster.go:231 +0xaa
github.com/exoscale/terraform-provider-exoscale/exoscale.resourceSKSNodepoolRead({0x1b42d20, 0xc0002e9620}, 0xc000183380, {0x19cce00, 0xc0005e20e0})
        github.com/exoscale/terraform-provider-exoscale/exoscale/resource_exoscale_sks_nodepool.go:313 +0x3f5
github.com/exoscale/terraform-provider-exoscale/exoscale.resourceSKSNodepoolCreate({0x1b42ce8, 0xc0006b4000}, 0xc0008d96c0, {0x19cce00, 0xc0005e20e0})
        github.com/exoscale/terraform-provider-exoscale/exoscale/resource_exoscale_sks_nodepool.go:299 +0x1065
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000436b60, {0x1b42c78, 0xc000580340}, 0x2, {0x19cce00, 0xc0005e20e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000436b60, {0x1b42c78, 0xc000580340}, 0xc0000fb790, 0xc000651d80, {0x19cce00, 0xc0005e20e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001234e8, {0x1b42c78, 0xc000580340}, 0xc00053a000)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000183580, {0x1b42d20, 0xc000881170}, 0xc000585810)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x19d0820, 0xc000183580}, {0x1b42d20, 0xc000881170}, 0xc000471620, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002f3dc0, {0x1b51ca8, 0xc0002a0780}, 0xc000904600, 0xc000452a20, 0x213b980, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0002f3dc0, {0x1b51ca8, 0xc0002a0780}, 0xc000904600, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-exoscale_v0.31.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Terraform version: v1.1.4 on darwin_amd64
Provider version: 0.31.2

I've tested the following resources:

exoscale_anti_affinity_group
exoscale_private_network
exoscale_security_group_rule
exoscale_security_group
exoscale_sks_cluster
exoscale_sks_nodepool

**Comment by mpalu** [comment]
An update that might be useful. This behavior doesn't happen when I create 1 nodepool per time, only when I try to create all the 12 at once.

**Comment by jessicatoscani** [comment]
@mpalu Thanks - we identified the pb and will fix it quickly.

**Comment by jessicatoscani** [comment]
The issue has been fixed (in our API). Don't hesitate to reopen the issue if you stumble on it again.
